apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  namespace: monit 
  name: monit 
  labels: 
    app: monit 
spec: 
  volumeName: "monit" 
  accessModes: 
  - ReadWriteMany 
  resources: 
    requests: 
      storage: "1Gi"
